### ISSUE TITLE
How to interact with Langchain?

### ISSUE THREAD

**Issue by dustinjoe** [lmstudio-ai/model-catalog#15]
Hi, thanks for the great tool of LMStudio. 
I am just wondering if there is any way to interact with Langchain using any way like API end point after the model is loaded?
Thank you!

**Comment by yagil** [comment]
Hi @dustinjoe yes there's a way. Someone shared some code on the LM Studio discord: https://discord.com/channels/1110598183144399058/1132309736059052182/1132343585023479951

You might need to join the server first via this link: https://discord.gg/aPQfnNkxGC

**Comment by yagil** [comment]
Closing this. If you need more help, reach out on Discord.

**Comment by dustinjoe** [comment]
Hi, really thanks for your reply. Sorry for late response. I just saw this notification.....
Will go to Discord for later communications. Thank you!

**Comment by yagil** [comment]
No problem @dustinjoe!
