### ISSUE TITLE
Add Mistral 7B Instruct

### ISSUE THREAD

**Issue by yagil** [lmstudio-ai/model-catalog#27]
Announcement: https://mistral.ai/news/announcing-mistral-7b/
Original model: https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.1
GGUF model: https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF

**Comment by mmagnesium** [comment]
Is it already possible to use this model? Or we need to wait for an update to support this architecture?

**Comment by yagil** [comment]
@mmagnesium it is already possible. This issue is tracking the TODO of adding it to the model catalog for convenience purposes.
