### ISSUE TITLE
any chance we will be able to pull up Ollama models soon???

### ISSUE THREAD

**Issue by cachatj** [lmstudio-ai/model-catalog#28]

**Comment by yagil** [comment]
@cachatj that’s an interesting questions. What’s the use case you envision?  Is it because there are models that aren’t on Hugging Face, or you after some other benefit?

**Comment by ianscrivener** [comment]
Ollama is an LLM inference app... just like LM Studio.
They both use the same underlying inference engine (llama.cpp) and the exact same models.. ie GGUFv2

So LM Studio (should) be able to use any model the Ollama uses. 
You may need to tweak the prompt
