### ISSUE TITLE
Loading issue of models

### ISSUE THREAD

**Issue by TWIISTED-STUDIOS** [lmstudio-ai/model-catalog#31]
How come if i copy a model i already have that works like wizard vic, but then I rename the copy to gpt-3.5-turbo-16k-0613 to be able to integrate with ChatDev and then change the corresponding .json file to the same name it will no longer load? how am I meant to rename a file to work with another API call if when you rename the file and the corresponding config it breaks the loading of that model?

**Comment by yagil** [comment]
The app presently relies on file path heuristics to deduce various datapoints about a given model file. It's not ideal, and hopefully we'll move to something more robust.

Do you have to rename the file? You can try to keep the original name as the folder name. For more in depth debugging, I recommend to join our discord server: https://discord.gg/aPQfnNkxGC
