### ISSUE TITLE
Model Download Failure

### ISSUE THREAD

**Issue by mk-bldn** [lmstudio-ai/model-catalog#36]
I'm attempting to download my first model with LM Studio. Unfortunately, when I select a model to download I get a "Failed" message immediately. Is there anywhere in the application where I can view the details of what is causing the download failure?... a log of some sort?

**Comment by tshrjn** [comment]
yaa, same here

**Comment by yagil** [comment]
There should be error logs in \AppData on Windows or ~/Library/Application Support on Mac.
For more debugging please join the [Discord](https://discord.gg/aPQfnNkxGC) and use the search function to find possible recourse.
