### ISSUE TITLE
Phi2 unknown model architecture

### ISSUE THREAD

**Issue by babycommando** [lmstudio-ai/model-catalog#55]
"failed to load model"

{
  "cause": "unknown model architecture: 'phi2'",
  "title": "Failed to load model",
  "errorData": {
    "n_ctx": 32768,
    "n_batch": 512,
    "n_gpu_layers": 0
  }
}

**Comment by yagil** [comment]
Hi @babycommando you need to update to LM Studio 0.2.10 for Phi 2 support.

**Comment by babycommando** [comment]
now that was fast! thank you and have a merry christmas!

**Comment by yagil** [comment]
🎅🎄🎁
